In [1]:
import pandas as pd

from evaluation_utils import (
    build_eval_artifacts,
    create_test_cases,
    evaluate_ndcg_at_5,
    compare_weight_configs,
)

In [ ]:
artifacts = build_eval_artifacts()

print("Eval-artifacts built.")
print(f"N movies in hybrid_features: {len(artifacts['hybrid_features'])}")
print(f"N movies in collaborative-index: {len(artifacts['movie_to_idx'])}")

Eval-artefacts built.
N movies in hybrid_features: 86537
N movies in collaborative-index: 15899

In [3]:
test_cases = create_test_cases(
    ratings=artifacts["ratings"],
    movie_to_idx=artifacts["movie_to_idx"],
    min_positive_movies=5,
    n_users=25,
    seed=42,
)

print(f"Number of test cases: {len(test_cases)}")
test_cases.head()

Number of test cases: 25

   userId  query_movie                                    relevant_movies
0  230534         2753  {423, 2600, 1961, 2762, 2700, 2605, 2706, 2580...
1  122674        27773  {1, 2571, 527, 97304, 3105, 3629, 50, 88125, 1...
2   66520          913  {33794, 2571, 527, 26131, 541, 29, 32, 26662, ...
3  258509          356  {736, 457, 588, 110, 527, 590, 592, 150, 153, ...
4   60263         1777                            {193, 1947, 1278, 2599}

In [ ]:
mean_ndcg_5 = evaluate_ndcg_at_5(
    test_cases=test_cases,
    hybrid_features=artifacts["hybrid_features"],
    tfidf_matrix=artifacts["tfidf_matrix"],
    item_user_matrix=artifacts["item_user_matrix"],
    movie_to_idx=artifacts["movie_to_idx"],
    idx_to_movie=artifacts["idx_to_movie"],
    knn_model=artifacts["knn_model"],
    collab_weight=0.3,
    content_weight=0.45,
    rating_weight=0.1,
    expert_weight=0.1,
    new_expert_weight=0.05,
    progress_every=5,
)

mean_ndcg_5

Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.

0.24804545604739917

In [ ]:
configs = [
    {
        "name": "baseline_current",
        "collab_weight": 0.3,
        "content_weight": 0.45,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "more_collab",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "balanced",
        "collab_weight": 0.35,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.15,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: baseline_current
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.
Running config: more_collab
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.
Running config: balanced
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,progress_every,ndcg_at_5
0,more_collab,0.40,0.35,0.1,0.10,0.05,5,0.364630
1,balanced,0.35,0.35,0.1,0.15,0.05,5,0.354591
2,baseline_current,0.30,0.45,0.1,0.10,0.05,5,0.248045

In [ ]:
configs = [
    {
        "name": "new_baseline (more_collab)",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "even_more_collab",
        "collab_weight": 0.5,
        "content_weight": 0.25,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "more_expert",
        "collab_weight": 0.30,
        "content_weight": 0.30,
        "rating_weight": 0.1,
        "expert_weight": 0.2,
        "new_expert_weight": 0.1,
        "progress_every": 5,
    },
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: new_baseline (more_collab)
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.
Running config: even_more_collab
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.
Running config: more_expert
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,progress_every,ndcg_at_5
0,new_baseline (more_collab),0.4,0.35,0.1,0.1,0.05,5,0.364630
1,even_more_collab,0.5,0.25,0.1,0.1,0.05,5,0.359381
2,more_expert,0.3,0.30,0.1,0.2,0.10,5,0.346787

In [ ]:
configs = [
    {
        "name": "new_baseline (more_collab)",
        "collab_weight": 0.4,
        "content_weight": 0.35,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "more_content",
        "collab_weight": 0.25,
        "content_weight": 0.5,
        "rating_weight": 0.1,
        "expert_weight": 0.1,
        "new_expert_weight": 0.05,
        "progress_every": 5,
    },
    {
        "name": "flat",
        "collab_weight": 0.2,
        "content_weight": 0.2,
        "rating_weight": 0.2,
        "expert_weight": 0.2,
        "new_expert_weight": 0.2,
        "progress_every": 5,
    },
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: new_baseline (more_collab)
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.
Running config: more_content
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.
Running config: flat
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,progress_every,ndcg_at_5
0,new_baseline (more_collab),0.40,0.35,0.1,0.1,0.05,5,0.364630
1,flat,0.20,0.20,0.2,0.2,0.20,5,0.357042
2,more_content,0.25,0.50,0.1,0.1,0.05,5,0.196713

In [ ]:
configs = [
    {"name" : "simple",
     "collab_weight" : 0.55,
     "content_weight" : 0.45,
     "rating_weight" : 0.0,
     "expert_weight" : 0.0,
     "new_expert_weight" : 0.0,
     "progress_every" : 5,
     }
]

results_df = compare_weight_configs(configs, test_cases, artifacts)
results_df

Running config: simple
Finished with 5/25 test cases.
Finished with 10/25 test cases.
Finished with 15/25 test cases.
Finished with 20/25 test cases.
Finished with 25/25 test cases.

,name,collab_weight,content_weight,rating_weight,expert_weight,new_expert_weight,progress_every,ndcg_at_5
0,simple,0.55,0.45,0.0,0.0,0.0,5,0.3625

Jag kommer fram till att den bästa configen av alla jag provat är "more_collab", och jag implementerar dessa vikter i min hybrid_model.